AppBundle\Entity\Order:
    type: entity
    table: orders
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        apiOrderId:
            type: integer
            nullable: false
            unsigned: false
            column: api_order_id
        customerId:
            type: integer
            nullable: false
            unsigned: false
            column: customer_id
        totalAmountNet:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            default: '0.00'
            column: total_amount_net
        shippingCosts:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            default: '0.00'
            column: shipping_costs
        discountValue:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            default: '0.00'
            column: discount_value
        paymentMethodId:
            type: integer
            nullable: false
            unsigned: false
            column: payment_method_id
    manyToOne:
        paymentMethod:
            targetEntity: PaymentMethod
            inversedBy: orders
            cascade: [ persist ]
            joinColumn:
                name: payment_method_id
                referencedColumnName: id
        customer:
            targetEntity: Customer
            inversedBy: orders
            cascade: [ persist ]
            joinColumn:
                name: customer_id
                referencedColumnName: id
    oneToMany:
        orderItems:
            targetEntity: OrderItem
            orphanRemoval: true
            mappedBy: order
            cascade: [ persist ]
    lifecycleCallbacks: {  }
