AppBundle\Entity\OrderItem:
    type: entity
    table: order_item
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        orderId:
            type: integer
            nullable: false
            unsigned: false
            column: order_id
        name:
            type: string
            nullable: false
            length: 250
            fixed: false
        quantity:
            type: integer
            nullable: false
            unsigned: false
        value:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
            default: '0'
        categoryId:
            type: integer
            nullable: false
            unsigned: false
            column: category_id
        subcategoryId:
            type: integer
            nullable: false
            unsigned: false
            column: subcategory_id
        collectionId:
            type: integer
            nullable: false
            unsigned: false
            column: collection_id
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: orderItems
            joinColumn:
                name: category_id
                referencedColumnName: id
    manyToOne:
        collection:
            targetEntity: Collection
            inversedBy: orderItems
            joinColumn:
                name: collection_id
                referencedColumnName: id
    manyToOne:
        subcategory:
            targetEntity: Subcategory
            inversedBy: orderItems
            joinColumn:
                name: subcategory_id
                referencedColumnName: id
    manyToOne:
        order:
            targetEntity: Order
            inversedBy: orderItems
            joinColumn:
                name: order_id
                referencedColumnName: id
    manyToMany:
        tags:
          targetEntity: Tag
          joinTable:
            name: order_item_tag
            joinColumns:
              order_item_id:
                referencedColumnName: id
            inverseJoinColumns:
              tag_id:
                referencedColumnName: id

    lifecycleCallbacks: {  }
